### ISSUE TITLE
Support new trade on market

### ISSUE THREAD

**Issue by girianshido** [gnosis/conditional-tokens-bot#12]
Get trades information from a given Market. Could there are two options:

- Listen a created contract `FixedProductMarketMaker` on the `FPMMBuy` and `FPMMSell` events from a given market address (returned by `FixedProductMarketMakerCreation` event). This will require to persist or get every created market address and watch it again after any restart.

- Query subgraph on a scheduled task to query for latest new trades. This will require a `Trade` entity to [subgrap] schema (https://github.com/protofire/omen-subgraph/blob/master/schema.graphql):
e.g:
```
{
  fixedProductMarketMakers(first: 10, orderBy: creationTimestamp, orderDirection: desc, where: {currentAnswer: null}) {
    id
    creationTimestamp
    scaledLiquidityMeasure
    collateralToken
    title
    outcomes
    currentAnswer
    participants {
      id
      
    }
  }
}
```

**Comment by auryn-macmillan** [comment]
@davidalbela my preference is for the subgraph option. Am I correct in understanding that this means we need to modify the subgraph?
cc @cag

**Comment by girianshido** [comment]
Yes, I'm afraid that, we need the info from trades when a `FPMMBuy` or `FPMMSell` event is triggered from a given `FixedProductMarketMaker`. Maybe we can add some `Trade` entity model [here](https://github.com/protofire/omen-subgraph/blob/master/src/FixedProductMarketMakerMapping.ts#L287) and [here](https://github.com/protofire/omen-subgraph/blob/master/src/FixedProductMarketMakerMapping.ts#L241).

**Comment by girianshido** [comment]
- **FPMMTrade** added to the Omen subgraph as a new PR: https://github.com/protofire/omen-subgraph/pull/65

It was also deployed on my own subgraphs for test on rinkeby and mainnet: 
- https://thegraph.com/explorer/subgraph/davidalbela/omen-rinkeby-trade?query=Example%20query
- https://thegraph.com/explorer/subgraph/davidalbela/omen-trade?query=Example%20query
